
multi_asset:
  enabled: true
  synergy_output_path: "data/intermediate/synergy_enriched.csv"

  hmm:
    n_states: 3
    covariance_type: "full"
    random_state: 42

  gnn:
    correlation_window: 30       # Rolling window for cross-asset correlation
    correlation_col: "log_return"
    correlation_threshold: 0.2   # GNN adjacency
    hidden_dim: 16
    num_layers: 2
    epochs: 50
    lr: 0.001
    synergy_loss: "mse"

    hyperparam_search:
      enabled: true
      n_trials: 10
      threshold_range: [0.05, 0.9]
      hidden_dim_range: [8, 64]