split:
  method: "date"
  train_cutoff: "2024-05-01"
  seq_len: 30
  all_features:
    - close
    - log_return
    - rv
    - bpv
    - park_vol
    - gk_vol
    - iqv
    - vov
    - time_since_open
  target_cols: ["rv", "iqv"]
  concurrency: 2

hyperparameter_search:
  enabled: true
  method: "deep"  # or "stochastic" or "both"
  n_trials: 20
  pruner: "median"   # or "none", "successive_halving", etc.

  deep_space:
    d_model: [8, 16, 32]
    learning_rate_log_range: [1.0e-4, 1.0e-2]
    epochs: 3

  stoch_space:
    wavelet_levels_choices: [3, 4, 5]
    random_restarts: [1, 2]